+incdir+../rtl/include
../rtl/include/definitions.sv
../rtl/compute/pe.sv
../rtl/compute/stream_if.sv
../rtl/compute/systolic_top.sv
../rtl/compute/fc_pe.sv
../rtl/compute/fc_systolic_array.sv
../rtl/compute/fc_accelerator_top.sv
../rtl/memory/global_buffer.sv
../rtl/memory/weight_buffer.sv
../rtl/memory/bias_buffer.sv
../rtl/memory/column_fifo.sv
../rtl/memory/input_buffer_bank.sv
../rtl/memory/fc_buffer.sv
../rtl/control/active_row_register.sv
../rtl/control/weight_scheduler.sv
../rtl/control/lenet5_controller.sv
../rtl/control/fc_controller.sv
../rtl/post_process/partial_sum_accumulator.sv
../rtl/post_process/pooling_core.sv
../rtl/post_process/pooling_top.sv
../rtl/post_process/result_handler.sv
../rtl/top/systolic_wrapper.sv
../rtl/top/lenet5_top.sv
../sim/tb_lenet5_top.sv
